In [7]:
import os
print(os.getcwd())

/Users/shivanshkhanna/traffic_hotspot_project

In [8]:
import os
print(os.getcwd())

/Users/shivanshkhanna/traffic_hotspot_project

In [12]:
import pandas as pd

df = pd.read_csv("data/raw/indian_roads_dataset.csv")
print(df)

       accident_id        city        state   latitude  longitude        date  \
0                0        Pune  Maharashtra  18.680827  73.930388  2023-10-22
1                1      Mumbai  Maharashtra  18.817732  72.790846  2023-05-21
2                2      Mumbai  Maharashtra  19.096889  72.819424  2024-07-10
3                3  Chandigarh       Punjab  30.787805  76.847507  2025-03-30
4                4     Chennai   Tamil Nadu  12.965155  80.283313  2024-01-25
...            ...         ...          ...        ...        ...         ...
19995        19995   Bangalore    Karnataka  13.092276  77.599571  2022-09-29
19996        19996     Chennai   Tamil Nadu  13.172928  80.157062  2023-11-25
19997        19997     Chennai   Tamil Nadu  12.997170  80.150724  2022-06-18
19998        19998     Kolkata  West Bengal  22.454882  88.322213  2023-03-12
19999        19999       Delhi        Delhi  28.510266  77.065301  2024-07-05

        time  hour day_of_week  is_weekend  ... visibility  temperature  \
0       5:00     5      Sunday           1  ...        low           32
1       4:00     4      Sunday           1  ...       high           34
2      13:00    13   Wednesday           0  ...        low           21
3      11:00    11      Sunday           1  ...        low           30
4      16:00    16    Thursday           0  ...       high           24
...      ...   ...         ...         ...  ...        ...          ...
19995   3:00     3    Thursday           0  ...       high           31
19996   1:00     1    Saturday           1  ...       high           20
19997  15:00    15    Saturday           1  ...       high           22
19998   4:00     4      Sunday           1  ...       high           33
19999  23:00    23      Friday           0  ...        low           39

       traffic_density         cause accident_severity  vehicles_involved  \
0                 high       weather             fatal                  2
1                  low       weather             major                  4
2               medium       weather             minor                  1
3                 high   distraction             minor                  5
4                  low   distraction             minor                  2
...                ...           ...               ...                ...
19995              low   distraction             minor                  3
19996              low   distraction             major                  4
19997              low       weather             minor                  3
19998              low     poor road             minor                  1
19999             high  overspeeding             minor                  4

      casualties is_peak_hour festival  risk_score
0              2            0      NaN        0.85
1              3            0      NaN        0.10
2              1            0      NaN        0.45
3              2            0      NaN        0.65
4              1            0      NaN        0.10
...          ...          ...      ...         ...
19995          2            0      NaN        0.10
19996          2            0      NaN        0.10
19997          3            0      NaN        0.10
19998          0            0      NaN        0.10
19999          2            0      NaN        0.65

[20000 rows x 24 columns]

In [13]:
df.head()

,accident_id,city,state,latitude,longitude,date,time,hour,day_of_week,is_weekend,...,visibility,temperature,traffic_density,cause,accident_severity,vehicles_involved,casualties,is_peak_hour,festival,risk_score
0,0,Pune,Maharashtra,18.680827,73.930388,2023-10-22,5:00,5,Sunday,1,...,low,32,high,weather,fatal,2,2,0,NaN,0.85
1,1,Mumbai,Maharashtra,18.817732,72.790846,2023-05-21,4:00,4,Sunday,1,...,high,34,low,weather,major,4,3,0,NaN,0.10
2,2,Mumbai,Maharashtra,19.096889,72.819424,2024-07-10,13:00,13,Wednesday,0,...,low,21,medium,weather,minor,1,1,0,NaN,0.45
3,3,Chandigarh,Punjab,30.787805,76.847507,2025-03-30,11:00,11,Sunday,1,...,low,30,high,distraction,minor,5,2,0,NaN,0.65
4,4,Chennai,Tamil Nadu,12.965155,80.283313,2024-01-25,16:00,16,Thursday,0,...,high,24,low,distraction,minor,2,1,0,NaN,0.10

In [19]:
df.tail

<bound method NDFrame.tail of        accident_id        city        state   latitude  longitude        date  \
0                0        Pune  Maharashtra  18.680827  73.930388  2023-10-22
1                1      Mumbai  Maharashtra  18.817732  72.790846  2023-05-21
2                2      Mumbai  Maharashtra  19.096889  72.819424  2024-07-10
3                3  Chandigarh       Punjab  30.787805  76.847507  2025-03-30
4                4     Chennai   Tamil Nadu  12.965155  80.283313  2024-01-25
...            ...         ...          ...        ...        ...         ...
19995        19995   Bangalore    Karnataka  13.092276  77.599571  2022-09-29
19996        19996     Chennai   Tamil Nadu  13.172928  80.157062  2023-11-25
19997        19997     Chennai   Tamil Nadu  12.997170  80.150724  2022-06-18
19998        19998     Kolkata  West Bengal  22.454882  88.322213  2023-03-12
19999        19999       Delhi        Delhi  28.510266  77.065301  2024-07-05

        time  hour day_of_week  is_weekend  ... visibility  temperature  \
0       5:00     5      Sunday           1  ...        low           32
1       4:00     4      Sunday           1  ...       high           34
2      13:00    13   Wednesday           0  ...        low           21
3      11:00    11      Sunday           1  ...        low           30
4      16:00    16    Thursday           0  ...       high           24
...      ...   ...         ...         ...  ...        ...          ...
19995   3:00     3    Thursday           0  ...       high           31
19996   1:00     1    Saturday           1  ...       high           20
19997  15:00    15    Saturday           1  ...       high           22
19998   4:00     4      Sunday           1  ...       high           33
19999  23:00    23      Friday           0  ...        low           39

       traffic_density         cause accident_severity  vehicles_involved  \
0                 high       weather             fatal                  2
1                  low       weather             major                  4
2               medium       weather             minor                  1
3                 high   distraction             minor                  5
4                  low   distraction             minor                  2
...                ...           ...               ...                ...
19995              low   distraction             minor                  3
19996              low   distraction             major                  4
19997              low       weather             minor                  3
19998              low     poor road             minor                  1
19999             high  overspeeding             minor                  4

      casualties is_peak_hour festival  risk_score
0              2            0      NaN        0.85
1              3            0      NaN        0.10
2              1            0      NaN        0.45
3              2            0      NaN        0.65
4              1            0      NaN        0.10
...          ...          ...      ...         ...
19995          2            0      NaN        0.10
19996          2            0      NaN        0.10
19997          3            0      NaN        0.10
19998          0            0      NaN        0.10
19999          2            0      NaN        0.65

[20000 rows x 24 columns]>

In [14]:
df.isnull().sum()

accident_id              0
city                     0
state                    0
latitude                 0
longitude                0
date                     0
time                     0
hour                     0
day_of_week              0
is_weekend               0
road_type                0
lanes                    0
traffic_signal           0
weather                  0
visibility               0
temperature              0
traffic_density          0
cause                    0
accident_severity        0
vehicles_involved        0
casualties               0
is_peak_hour             0
festival             19885
risk_score               0
dtype: int64

In [21]:
df.columns.to_list()

['accident_id',
 'city',
 'state',
 'latitude',
 'longitude',
 'date',
 'time',
 'hour',
 'day_of_week',
 'is_weekend',
 'road_type',
 'lanes',
 'traffic_signal',
 'weather',
 'visibility',
 'temperature',
 'traffic_density',
 'cause',
 'accident_severity',
 'vehicles_involved',
 'casualties',
 'is_peak_hour',
 'festival',
 'risk_score']

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df["accident_severity"].value_counts()

accident_severity
minor    11025
major     5988
fatal     2987
Name: count, dtype: int64

In [18]:
df["state"].value_counts()

state
Maharashtra    5009
Punjab         2577
Tamil Nadu     2575
West Bengal    2559
Karnataka      2438
Delhi          2433
Telangana      2409
Name: count, dtype: int64

In [22]:
print(df["city"].nunique())

df["city"].value_counts().head(20)

8

city
Chandigarh    2577
Chennai       2575
Kolkata       2559
Pune          2517
Mumbai        2492
Bangalore     2438
Delhi         2433
Hyderabad     2409
Name: count, dtype: int64

In [23]:
audit = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.values,
    "Missing": df.isnull().sum().values,
    "Unique Values": df.nunique().values
})

audit

               Column Data Type  Missing  Unique Values
0         accident_id     int64        0          20000
1                city    object        0              8
2               state    object        0              7
3            latitude   float64        0          19907
4           longitude   float64        0          19927
5                date    object        0           1201
6                time    object        0             24
7                hour     int64        0             24
8         day_of_week    object        0              7
9          is_weekend     int64        0              2
10          road_type    object        0              3
11              lanes     int64        0              6
12     traffic_signal     int64        0              2
13            weather    object        0              3
14         visibility    object        0              3
15        temperature     int64        0             26
16    traffic_density    object        0              3
17              cause    object        0              5
18  accident_severity    object        0              3
19  vehicles_involved     int64        0              5
20         casualties     int64        0              6
21       is_peak_hour     int64        0              2
22           festival    object    19885              4
23         risk_score   float64        0             18

In [24]:
audit.to_csv("reports/data_audit.csv", index=False)